### ISSUE TITLE
Separate current and past hackathons

### ISSUE THREAD

**Issue by jamy015** [leonoverweel/dutch-hackathons#1]
IMO, it should be easy to see which hackathons I can still go to. I propose creating a separate section for past hackathons that haven't announced a future version.

**Comment by leonoverweel** [comment]
Hmm yeah I was thinking about this. My thoughts were to add the exact date in parentheses for hackathons that are coming up, as such:

| Hackathon | Location | Years
|---|---|---|
| [World Port Hackathon](http://worldporthackathon.com/) | Rotterdam | 2013, 2014, [2015](http://www.worldporthackathon.com/2015/), [2016](http://www.worldporthackathon.com/2016/), 2017 (September 1 & 2) |

What do you think @jamy015?

**Comment by jamy015** [comment]
I agree that adding the exact date is probably pretty useful. Maybe we could split the future dates in a separate column so it's nice and easy to read, like this:

> | Hackathon | Location | Past editions | Future editions
> |---|---|---|---|
> | World Port Hackathon | Rotterdam | 2013, 2014, 2015, 2016 | 2017 (September 1 & 2)
> | HEX | Eindhoven | 2017 |

That also makes explicit which hackathons in \<current year\> have already taken place. However, if we want to prevent ugly gaps in the table, we have to then sort them by date instead of alphabetically.
